#!/bin/bash
#PBS -N s2048_1dr0_o32
#PBS -A Abacus
#PBS -l select=8:ncpus=64:mpiprocs=2:ompthreads=32
#PBS -l walltime=00:15:00
#PBS -q debug-scaling
#PBS -l filesystems=home
#PBS -M helenshao0904@gmail.com
#PBS -m abe
#PBS -j oe
#PBS -o /home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/N2048_CPD225_MPI32_OMP32.out
cd "$PBS_O_WORKDIR"
module load frameworks && module load fftw/3.3.10 && module load hwloc
cd /home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production
NTOTRANKS=$( [ -f "$PBS_NODEFILE" ] && wc -l < "$PBS_NODEFILE" || echo 16 ); NTHREADS_PER_RANK=32; N=2048
source "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/scripts/meson_build_zmpi.sh"
cp "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/metadata/param_N2048_CPD_225.par" "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/param_runtime_OMP32.par"
sed -i "s|^InitialConditionsDirectory[[:space:]]*=.*$|InitialConditionsDirectory = \"/lus/flare/projects/AbacusAurora/hshao/zeldovich-MPI/PPD_2048_cosm_000/z_24/rank0-loads/omp-32/\"|" "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/param_runtime_OMP32.par"
mkdir -p "/lus/flare/projects/AbacusAurora/hshao/zeldovich-MPI/PPD_2048_cosm_000/z_24/rank0-loads/omp-32" "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/bin_files" "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/rng_logs"
cd "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/bin_files"
export OMP_PLACES=cores OMP_PROC_BIND=close OMP_DISPLAY_AFFINITY=false OMP_NUM_THREADS=$NTHREADS_PER_RANK
"$WISDOM_EXE" 2048 4 >> "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/N2048_CPD225_MPI32_OMP32_wisdom_preflight.log" 2>&1
mpiexec -ppn 2 --cpu-bind depth --depth $NTHREADS_PER_RANK --mem-bind list:0:1 -np $NTOTRANKS --env OMP_NUM_THREADS=$NTHREADS_PER_RANK --env OMP_PLACES=cores --env OMP_PROC_BIND=close --env OMP_DISPLAY_AFFINITY=false "$ZMPI_EXE" $N "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/param_runtime_OMP32.par" > "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/N2048_CPD225_MPI32_OMP32_bin_generation.log" 2> "/home/helenshao/InitialConditions-wisdom/hermitian_3d_matrix_production/test_N2048/rank0-loads/MEASURE/runs/omp-32/rng_logs/zd_mpi_rng_debug.log"
